In [1]:
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [2]:
import pandas as pd
import numpy as np

In [3]:
train_data=pd.read_csv("train.csv")
test_data=pd.read_csv("test.csv")

In [4]:
train_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
X_train=train_data[['PassengerId', 'Pclass', 'Sex', 'Age']]
X_test=test_data[['PassengerId', 'Pclass', 'Sex', 'Age']]
test_output=pd.read_csv("pred.csv")

In [6]:
y_train=train_data["Survived"]

In [7]:
X_train.isnull().sum()

PassengerId      0
Pclass           0
Sex              0
Age            177
dtype: int64

In [8]:
X_train=X_train.fillna(method="bfill")

In [9]:
X_train["Sex"]=(X_train["Sex"]=="male").astype(int)

In [10]:
X_train.head()

PassengerId  Pclass  Sex   Age
0            1       3    1  22.0
1            2       1    0  38.0
2            3       3    0  26.0
3            4       1    0  35.0
4            5       3    1  35.0

In [11]:
X_test=X_test.fillna(method="bfill")
X_test["Sex"]=(X_test["Sex"]=="male").astype(int)


In [12]:
X_test=X_test.fillna(method="ffill")

In [13]:
y_test=test_output["Survived"]

In [14]:
model=DTC()
model2=DTC(criterion='entropy',splitter="random",max_depth=3)

In [15]:
model.fit(X_train,y_train)
model2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='random')

In [16]:
pred=model.predict(X_test)
pred2=model2.predict(X_test)

In [17]:
acc=accuracy_score(y_test,pred)
acc2=accuracy_score(y_test,pred2)


In [18]:
print(acc,acc2)

0.7918660287081339 0.8277511961722488


In [19]:
model.predict_proba([[5,2,0,35.0]])

array([[0., 1.]])

In [20]:
model.predict([[5,2,0,35.0]])

array([1], dtype=int64)

In [24]:
print(precision_score(y_test,pred),precision_score(y_test,pred2))

0.7210884353741497 1.0


In [25]:
print(recall_score(y_test,pred),recall_score(y_test,pred))

0.6973684210526315 0.6973684210526315


In [26]:
print(f1_score(y_test,pred),f1_score(y_test,pred))

0.7090301003344481 0.7090301003344481


In [27]:
confusion_matrix(y_test,pred)

array([[225,  41],
       [ 46, 106]], dtype=int64)

In [28]:
confusion_matrix(y_test,pred2)

array([[266,   0],
       [ 72,  80]], dtype=int64)